anguage: c
notifications:
  recipients:
    - kenhys@gmail.com
install:
  - sudo apt-get install -y autotools-dev intltool
  - sudo apt-get install -y ttf-takao ttf-umefont ttf-umeplus ttf-vlgothic
before_script:
  - echo "before_scriot"
  - curl http://packages.groonga.org/tmp/setup.sh | sh
#  - curl https://raw.github.com/groonga/groonga/master/data/travis/setup.sh | sh
script:
  - echo "script"

